### PR TITLE
Added support for configuring desired Sealed HTTP response status code

### PR DESCRIPTION
**Pull request by aantono**
for /status.json when VGM is in Sealed status, allow configuring desired HTTP status code, for example, instead of default 200, use 429, or something like that.

### CODE REVIEW

**Comment by nemosupremo** [comment]
Hey thanks for PR. 

Would you mind changing this PR to not include the changes to `build.bash`?

**Comment by aantono** [comment]
You bet.  Should I open a different PR with the build.bash changes to add ability to build multiple binaries?

**Comment by nemosupremo** [comment]
Yep, thanks.

**Comment by aantono** [comment]
Awesome, thanks for a quick turn around.  Opened another PR.

**Pull request merged**
