### PR TITLE
Added support for ECS Provider + AWS EC2 pkcs7 auth + Test Provider

### PR DESCRIPTION
**Pull request by aantono**

### CODE REVIEW

**Comment by broamski** [comment]
I like the idea of supporting ECS! I don't want to speak for @nemosupremo, but I think there will need to be some discussions around documentation, naming, and references, before this proceeds. I'll volunteer my time if we want to put together a plan.

**Comment by nemosupremo** [comment]
Thanks aantono. A short while after building this project I realized I *should* have architected it in such a way that didn't marry the design to mesos, so platforms like ECS or k8s could be supported as well. I've meant to rework the basic design, but I've never gotten the time.

Essentially, as you may have come across, the mesos architecture could be abstracted out to support any type of "custom" token authorization schemes. As you probably discovered, there is a gatekeeper frontend and potentially multiple provider backends (currently there is only one provider - mesos). The `Provider` interface should have

* Initialize - Initialize the provider with required settings (hostnames, certs)
* Unseal - Provide the necessary tokens required for making authorized requests to the backend (ex. Mesos Root Token)
* Seal
* Authorize - This function given some sort of identifier, checks the identifier to make sure a token can be released. (ex. a task id, which the authorize function would check that the task exists and has  been running for <X minutes).

The goal should be that its very simple to add & test new provider backends, while separating out the actual Vault concerns from them. 

*However*, in the mean time I'll look into merging this. I generally believe perfect is the enemy of good, and this project is small enough that we can live with *some* technical debt until the rewrite is complete. In the mean time, we can certainly discuss an architecture for a plan to support more providers that is also easy to extend. I'm currently on a business trip to Europe (for the past 4 weeks 😓), but I'll keep track of that progress in #14

**Comment by aantono** [comment]
Thanks @nemosupremo.  I've tried to create a light layer of abstraction for the Provider (not a full-blown interface), so not sure if this is up to par with what you were expecting.  I've basically noticed that you were already creating a different function binding for `gMT` function, which returns the task data.  I took that and created 3 different functions, one for `mesos`, `ecs` and `test` that call the appropriate backends to extract the data for the provided `taskId`.

Maybe we can use this as a basis foundation to pull things further apart and introduce the other concepts as we go?

Let me know what you think and would like to hear your feedback on the PR.

Looking forward working on making this library more powerful!

**Comment by aantono** [comment]
Any updates on this PR?

**Pull request merged**
